
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Mauricio, Lidiane, Adan, Igor
 */
public class CadastroPessoaJuridica extends javax.swing.JInternalFrame {
    ValidaEmail valida = new ValidaEmail();

    /**
     * Creates new form PessoaJuridica
     */
    public CadastroPessoaJuridica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupTributarias = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        txtNomeEmpresa = new javax.swing.JTextField();
        txtRazaoSocial = new javax.swing.JTextField();
        lblNomeEmpresa = new javax.swing.JLabel();
        lblRazaoSocial = new javax.swing.JLabel();
        lblIE = new javax.swing.JLabel();
        lblInfoTributarias = new javax.swing.JLabel();
        rbtContribuinteICMS = new javax.swing.JRadioButton();
        rbtNaoContribuinte = new javax.swing.JRadioButton();
        rbtIsentoIE = new javax.swing.JRadioButton();
        lblCNPJ = new javax.swing.JLabel();
        ftxtCNPJ = new javax.swing.JFormattedTextField();
        lblContato = new javax.swing.JLabel();
        txtContato = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        ftxtEmail = new javax.swing.JFormattedTextField();
        lblTel1 = new javax.swing.JLabel();
        lblTel2 = new javax.swing.JLabel();
        ftxtTel1 = new javax.swing.JFormattedTextField();
        ftxtTel2 = new javax.swing.JFormattedTextField();
        jLblValida = new javax.swing.JLabel();
        ftxtIE = new javax.swing.JFormattedTextField();
        jPanel5 = new javax.swing.JPanel();
        lblTipoEndereco = new javax.swing.JLabel();
        ComboEnd = new javax.swing.JComboBox();
        lblCEP = new javax.swing.JLabel();
        lblBairro = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        ComboEstado = new javax.swing.JComboBox();
        ftxtCEP = new javax.swing.JFormattedTextField();
        txtBairro = new javax.swing.JTextField();
        lblCidade = new javax.swing.JLabel();
        lblRua = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        txtRua = new javax.swing.JTextField();
        lblComplemento = new javax.swing.JLabel();
        txtComplemanto = new javax.swing.JTextField();
        lblNumero = new javax.swing.JLabel();
        ftxtNumero = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        btnSair = new javax.swing.JButton();
        btnConcluirC = new javax.swing.JButton();

        setTitle("Cadastro de Pessoas Juridicas");

        txtNomeEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeEmpresaActionPerformed(evt);
            }
        });
        txtNomeEmpresa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomeEmpresaKeyTyped(evt);
            }
        });

        txtRazaoSocial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRazaoSocialKeyTyped(evt);
            }
        });

        lblNomeEmpresa.setText("Nome da Empresa: ");

        lblRazaoSocial.setText("Razão Social:");

        lblIE.setText("Inscrição Estadual:");

        lblInfoTributarias.setText("Informações Tributarias: ");

        groupTributarias.add(rbtContribuinteICMS);
        rbtContribuinteICMS.setText("Contribuinte icms");

        groupTributarias.add(rbtNaoContribuinte);
        rbtNaoContribuinte.setText("Não contribuinte");

        groupTributarias.add(rbtIsentoIE);
        rbtIsentoIE.setText("Isento de inscrição estadual");

        lblCNPJ.setText("CNPJ:");

        try {
            ftxtCNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblContato.setText("Contato:");

        txtContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContatoActionPerformed(evt);
            }
        });
        txtContato.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtContatoKeyTyped(evt);
            }
        });

        lblEmail.setText("Email:");

        ftxtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ftxtEmailFocusLost(evt);
            }
        });

        lblTel1.setText("Telefone1:");

        lblTel2.setText("Telefone2:");

        try {
            ftxtTel1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            ftxtTel2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            ftxtIE.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###.###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblContato)
                        .addGap(38, 38, 38)
                        .addComponent(txtContato, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblInfoTributarias)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(rbtContribuinteICMS)
                                .addGap(18, 18, 18)
                                .addComponent(rbtNaoContribuinte)
                                .addGap(18, 18, 18)
                                .addComponent(rbtIsentoIE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCNPJ)
                                    .addComponent(lblNomeEmpresa)
                                    .addComponent(lblRazaoSocial)
                                    .addComponent(lblIE))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNomeEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                                    .addComponent(ftxtCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtRazaoSocial)
                                    .addComponent(ftxtIE))))
                        .addContainerGap(158, Short.MAX_VALUE))))
            .addComponent(jSeparator1)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTel1)
                    .addComponent(lblEmail)
                    .addComponent(lblTel2))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ftxtTel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(ftxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jLblValida, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(ftxtTel2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeEmpresa)
                    .addComponent(txtNomeEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRazaoSocial)
                    .addComponent(txtRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCNPJ)
                    .addComponent(ftxtCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIE)
                    .addComponent(ftxtIE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInfoTributarias)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtContribuinteICMS)
                    .addComponent(rbtNaoContribuinte)
                    .addComponent(rbtIsentoIE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblContato))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblEmail)
                                    .addComponent(ftxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(lblTel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ftxtTel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLblValida, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTel2)
                    .addComponent(ftxtTel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Dados da Empresa", jPanel3);

        lblTipoEndereco.setText("Tipo de Endereço:");

        ComboEnd.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ap Comercial", "Comercio", "Outros" }));
        ComboEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboEndActionPerformed(evt);
            }
        });

        lblCEP.setText("CEP:");

        lblBairro.setText("Bairro:");

        lblEstado.setText("Estado:");

        ComboEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        try {
            ftxtCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        txtBairro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBairroKeyTyped(evt);
            }
        });

        lblCidade.setText("Cidade:");

        lblRua.setText("Rua:");

        txtCidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCidadeKeyTyped(evt);
            }
        });

        txtRua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRuaKeyTyped(evt);
            }
        });

        lblComplemento.setText("Complemento:");

        lblNumero.setText("Numero:");

        ftxtNumero.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEstado)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTipoEndereco)
                                    .addComponent(lblCEP))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ComboEnd, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ftxtCEP))))
                        .addGap(84, 491, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCidade)
                            .addComponent(lblRua)
                            .addComponent(lblComplemento))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(ComboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtComplemanto, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtRua, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                                    .addComponent(txtCidade))
                                .addGap(51, 51, 51)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblBairro)
                                    .addComponent(lblNumero))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtBairro, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(ftxtNumero))
                                .addGap(71, 71, 71))))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoEndereco)
                    .addComponent(ComboEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCEP)
                    .addComponent(ftxtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstado)
                    .addComponent(ComboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCidade)
                    .addComponent(lblBairro)
                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRua)
                    .addComponent(txtRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftxtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumero))
                .addGap(25, 25, 25)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblComplemento)
                    .addComponent(txtComplemanto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(116, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Endereço", jPanel5);

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnConcluirC.setText("Concluir cadastro");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConcluirC)
                .addGap(18, 18, 18)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSair)
                    .addComponent(btnConcluirC, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboEndActionPerformed
        // combo box endereço pessoa fisica
    }//GEN-LAST:event_ComboEndActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // Botao sair frame pessoa juridica
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void ftxtTel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftxtTel1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftxtTel1ActionPerformed

    private void txtNomeEmpresaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeEmpresaKeyTyped
    //validando para nao aceitar numero no campo Nome da Empresa
        try {
            String caracteres = "0987654321";
            if (caracteres.contains(evt.getKeyChar() + "")) {
                evt.consume();
            }
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, "Informação inserida não está correto!!!", "Erro", JOptionPane.OK_OPTION, JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_txtNomeEmpresaKeyTyped

    private void txtRazaoSocialKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRazaoSocialKeyTyped
       //validando para nao aceitar numero no campo Razão Social
        try {
            String caracteres = "0987654321";
            if (caracteres.contains(evt.getKeyChar() + "")) {
                evt.consume();
            }
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, "Informação inserida não está correto!!!", "Erro", JOptionPane.OK_OPTION, JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_txtRazaoSocialKeyTyped

    private void txtNomeEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeEmpresaActionPerformed

    private void txtRazaoSocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRazaoSocialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRazaoSocialActionPerformed

    private void txtResponsavelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtResponsavelKeyTyped
      // validando para não aceitar número no campo Responsável
        try {
            String caracteres = "0987654321";
            if (caracteres.contains(evt.getKeyChar() + "")) {
                evt.consume();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Informação inserida não está correto!!!");
        }
    }//GEN-LAST:event_txtResponsavelKeyTyped

    private void ftxtCNPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftxtCNPJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftxtCNPJActionPerformed

    private void txtResponsavelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResponsavelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResponsavelActionPerformed

    private void ftxtCidadeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ftxtCidadeKeyTyped
 // validando para não aceitar numero no campo Cidade
        try {
            String caracteres = "0987654321";
            if (caracteres.contains(evt.getKeyChar() + "")) {
                evt.consume();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Informação inserida não está correto!!!");
        }
    }//GEN-LAST:event_ftxtCidadeKeyTyped

    private void ftxtBairroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ftxtBairroKeyTyped
    // validando para não aceitar numero no campo Bairro
        try {
            String caracteres = "0987654321";
            if (caracteres.contains(evt.getKeyChar() + "")) {
                evt.consume();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Informação inserida não está correto!!!");
        }
    }//GEN-LAST:event_ftxtBairroKeyTyped

    private void ftxtRuaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ftxtRuaKeyTyped
   // validando para não aceitar numero no campo Rua
        try {
            String caracteres = "0987654321";
            if (caracteres.contains(evt.getKeyChar() + "")) {
                evt.consume();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Informação inserida não está correto!!!");
        }
    }//GEN-LAST:event_ftxtRuaKeyTyped

    private void txtContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContatoActionPerformed

    private void txtContatoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContatoKeyTyped
 //validando para nao aceitar numero no campo Contato
        try {
            String caracteres = "0987654321";
            if (caracteres.contains(evt.getKeyChar() + "")) {
                evt.consume();
            }
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, "Informação inserida não está correto!!!", "Erro", JOptionPane.OK_OPTION, JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_txtContatoKeyTyped

    private void ftxtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftxtEmailFocusLost
     // Validando email
        String email = ftxtEmail.getText();
        
         //Valida email
        boolean validaemail = valida.validaEmail(email);

        if (validaemail == true) {
            //jLblValida.setText(certo);
            jLblValida.setIcon(new ImageIcon(getClass().getResource("/Icones/Certo.png")));
        } else {
            // jLblValida.setText("E-Mail Incorreto!");
            jLblValida.setIcon(new ImageIcon(getClass().getResource("/Icones/Errado.png")));
        }
    }//GEN-LAST:event_ftxtEmailFocusLost

    private void txtCidadeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCidadeKeyTyped
        // try catch oara não aceitar int no campo Cidade
        
        try {
            String caracteres = "0987654321";
            if (caracteres.contains(evt.getKeyChar() + "")) {
                evt.consume();
            }
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, "Informação inserida não está correto!!!", "Erro", JOptionPane.OK_OPTION, JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_txtCidadeKeyTyped

    private void txtBairroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBairroKeyTyped
      // try catch para não aceitar int no campo Bairro
        
        try {
            String caracteres = "0987654321";
            if (caracteres.contains(evt.getKeyChar() + "")) {
                evt.consume();
            }
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, "Informação inserida não está correto!!!", "Erro", JOptionPane.OK_OPTION, JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_txtBairroKeyTyped

    private void txtRuaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRuaKeyTyped
        // try catch oara não aceitar int no campo Rua
        
        try {
            String caracteres = "0987654321";
            if (caracteres.contains(evt.getKeyChar() + "")) {
                evt.consume();
            }
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, "Informação inserida não está correto!!!", "Erro", JOptionPane.OK_OPTION, JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_txtRuaKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ComboEnd;
    private javax.swing.JComboBox ComboEstado;
    private javax.swing.JButton btnConcluirC;
    private javax.swing.JButton btnSair;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JFormattedTextField ftxtCEP;
    private javax.swing.JFormattedTextField ftxtCNPJ;
    private javax.swing.JFormattedTextField ftxtEmail;
    private javax.swing.JFormattedTextField ftxtIE;
    private javax.swing.JFormattedTextField ftxtNumero;
    private javax.swing.JFormattedTextField ftxtTel1;
    private javax.swing.JFormattedTextField ftxtTel2;
    private javax.swing.ButtonGroup groupTributarias;
    private javax.swing.JLabel jLblValida;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCEP;
    private javax.swing.JLabel lblCNPJ;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblComplemento;
    private javax.swing.JLabel lblContato;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblIE;
    private javax.swing.JLabel lblInfoTributarias;
    private javax.swing.JLabel lblNomeEmpresa;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblRazaoSocial;
    private javax.swing.JLabel lblRua;
    private javax.swing.JLabel lblTel1;
    private javax.swing.JLabel lblTel2;
    private javax.swing.JLabel lblTipoEndereco;
    private javax.swing.JRadioButton rbtContribuinteICMS;
    private javax.swing.JRadioButton rbtIsentoIE;
    private javax.swing.JRadioButton rbtNaoContribuinte;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtComplemanto;
    private javax.swing.JTextField txtContato;
    private javax.swing.JTextField txtNomeEmpresa;
    private javax.swing.JTextField txtRazaoSocial;
    private javax.swing.JTextField txtRua;
    // End of variables declaration//GEN-END:variables
}
