
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Adan, Mauricio, Igor, Lid
 */
public class CadastroClientePessoaFisica extends javax.swing.JInternalFrame {

    ValidaEmail valida = new ValidaEmail();

    /**
     * Creates new form Cadastro3
     */
    public CadastroClientePessoaFisica() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngSexo = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        txtdataNasc = new javax.swing.JFormattedTextField();
        lblDataNasc = new javax.swing.JLabel();
        rbtMasculino = new javax.swing.JRadioButton();
        rbtFeminino = new javax.swing.JRadioButton();
        lblSexo = new javax.swing.JLabel();
        rbtOutro = new javax.swing.JRadioButton();
        lblCPF = new javax.swing.JLabel();
        ftxtCPF = new javax.swing.JFormattedTextField();
        lblTel1 = new javax.swing.JLabel();
        lblTel2 = new javax.swing.JLabel();
        ftxtTel1 = new javax.swing.JFormattedTextField();
        ftxtTel2 = new javax.swing.JFormattedTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblContato = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        jLblValida = new javax.swing.JLabel();
        txtNomeCompleto2 = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lblTipoEndereco = new javax.swing.JLabel();
        ComboEnd = new javax.swing.JComboBox();
        lblCEP = new javax.swing.JLabel();
        lblBairro = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        ComboEstado = new javax.swing.JComboBox();
        ftxtCEP = new javax.swing.JFormattedTextField();
        txtBairro = new javax.swing.JTextField();
        lblCidade = new javax.swing.JLabel();
        lblRua = new javax.swing.JLabel();
        txtRua = new javax.swing.JTextField();
        lblComplemento = new javax.swing.JLabel();
        txtComplemento = new javax.swing.JTextField();
        lblNumero = new javax.swing.JLabel();
        ftxtNumero = new javax.swing.JFormattedTextField();
        ftxtCidade = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        btnSair = new javax.swing.JButton();
        btnConcluirC = new javax.swing.JButton();

        setBorder(null);
        setTitle("Cadastro de Pessoas Fisicas");

        lblNome.setText("Nome Completo:");

        txtdataNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.MEDIUM))));
        txtdataNasc.setText("DD/MM/YYYY");
        txtdataNasc.setToolTipText("");
        txtdataNasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdataNascActionPerformed(evt);
            }
        });
        txtdataNasc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtdataNascFocusGained(evt);
            }
        });

        lblDataNasc.setText("Data Nascimento:");

        btngSexo.add(rbtMasculino);
        rbtMasculino.setText("Masculino");

        btngSexo.add(rbtFeminino);
        rbtFeminino.setText("Feminido");

        lblSexo.setText("Sexo:");

        btngSexo.add(rbtOutro);
        rbtOutro.setText("Outro");

        lblCPF.setText("CPF:");

        try {
            ftxtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblTel1.setText("Telefone 1:");

        lblTel2.setText("Telefone 2: ");

        try {
            ftxtTel1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            ftxtTel2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblContato.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblContato.setText("Contato");

        lblEmail.setText("Email: ");

        txtNomeCompleto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeCompleto2ActionPerformed(evt);
            }
        });
        txtNomeCompleto2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomeCompleto2KeyTyped(evt);
            }
        });

        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDataNasc)
                    .addComponent(lblCPF)
                    .addComponent(lblNome, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNomeCompleto2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ftxtCPF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                            .addComponent(txtdataNasc, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(123, 123, 123)
                        .addComponent(lblSexo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtMasculino)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtFeminino)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtOutro)))
                .addContainerGap(97, Short.MAX_VALUE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblContato))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblTel2)
                                .addComponent(lblTel1, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(lblEmail)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLblValida, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(ftxtTel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                                .addComponent(ftxtTel2, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addGap(0, 168, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeCompleto2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtdataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDataNasc)
                    .addComponent(rbtMasculino)
                    .addComponent(rbtFeminino)
                    .addComponent(lblSexo)
                    .addComponent(rbtOutro))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCPF)
                    .addComponent(ftxtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(lblContato)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(jLblValida, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTel1)
                    .addComponent(ftxtTel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTel2)
                    .addComponent(ftxtTel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(93, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Dados Pessoais", jPanel1);

        lblTipoEndereco.setText("Tipo de Endereço:");

        ComboEnd.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Selecionar--", "Casa ", "Apartamento", "Comercial", "Outros" }));
        ComboEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboEndActionPerformed(evt);
            }
        });

        lblCEP.setText("CEP:");

        lblBairro.setText("Bairro:");

        lblEstado.setText("Estado:");

        ComboEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Selecionar--", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        try {
            ftxtCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxtCEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftxtCEPActionPerformed(evt);
            }
        });

        txtBairro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBairroKeyTyped(evt);
            }
        });

        lblCidade.setText("Cidade:");

        lblRua.setText("Rua:");

        txtRua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRuaKeyTyped(evt);
            }
        });

        lblComplemento.setText("Complemento:");

        lblNumero.setText("Numero:");

        ftxtNumero.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        ftxtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftxtNumeroActionPerformed(evt);
            }
        });
        ftxtNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ftxtNumeroKeyTyped(evt);
            }
        });

        ftxtCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftxtCidadeActionPerformed(evt);
            }
        });
        ftxtCidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ftxtCidadeKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEstado)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTipoEndereco)
                                    .addComponent(lblCEP))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ComboEnd, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ftxtCEP))))
                        .addGap(84, 492, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCidade)
                            .addComponent(lblRua)
                            .addComponent(lblComplemento))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtComplemento)
                                .addGap(342, 342, 342))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(ComboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtRua, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                    .addComponent(ftxtCidade))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblBairro)
                                    .addComponent(lblNumero))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtBairro, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(ftxtNumero))
                                .addGap(71, 71, 71))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoEndereco)
                    .addComponent(ComboEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCEP)
                    .addComponent(ftxtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstado)
                    .addComponent(ComboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCidade)
                    .addComponent(lblBairro)
                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftxtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRua)
                            .addComponent(txtRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNumero)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(ftxtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblComplemento)
                    .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(115, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Endereço", jPanel2);

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnConcluirC.setText("Concluir cadastro");
        btnConcluirC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConcluirCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConcluirC)
                .addGap(37, 37, 37)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConcluirC, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // Botao sair

        int op = JOptionPane.showConfirmDialog(null, "Tem certeza que quer sair dessa pagina?", "Confirmação", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        switch (op) {

            case 0:
                this.dispose();
                break;
        }
    }//GEN-LAST:event_btnSairActionPerformed

    private void ComboEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboEndActionPerformed
        // combo box endereço pessoa fisica

    }//GEN-LAST:event_ComboEndActionPerformed

    private void btnConcluirCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConcluirCActionPerformed
        // Botao concluir cadastro

        
        //informações dos campos para o BD
        RNClienteFisico r = new RNClienteFisico(" ", " ", " ", " ", " ", " ", " ");
        r.setTel1(ftxtTel1.getText());
        r.setTel2(ftxtTel2.getText());
        r.setEmail(txtEmail.getText());
        r.setNomeCompleto(txtNomeCompleto2.getText());
        r.setDataDeNascimento(txtdataNasc.getText());
        r.setCpf(ftxtCPF.getText());

        //radio button(campo de sexo do cadastro
        if (rbtMasculino.isSelected()) {
            r.setSexo("M");
        } else if (rbtFeminino.isSelected()) {
            r.setSexo("F");
        } else {
            r.setSexo("ND");
        }

        ConexaoBDFisico c = new ConexaoBDFisico();

        //confirmar o cadastro
        int i = JOptionPane.showConfirmDialog(rootPane, "Deseja salvar esse cadastro?"+ "\n Nome: "
                +r.getNomeCompleto()+ "\n Data de Nascimento: "+ r.getDataDeNascimento()+ "\n CPF: "
                + r.getCpf()+"\n Sexo: " +r.getSexo()+"\n Email: " + r.getEmail()+ "\n Telefone 1: " 
                + r.getTel1()+ "\n Telefone 2: " + r.getTel2(),
                "Confirmação", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        //condição para salvar no banco de dados
        if (i == JOptionPane.NO_OPTION) {
            JOptionPane.showMessageDialog(null, "Cadastro não foi salvo");
        } else {
            c.salvarCliente(r);
            JOptionPane.showMessageDialog(null, "Cadastro salvo com sucesso");
        }


    }//GEN-LAST:event_btnConcluirCActionPerformed


    private void txtNomeCompleto2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeCompletoKeyTyped
        //validando para nao aceitar numero no campo nome completo
        try {
            String caracteres = "0987654321";
            if (caracteres.contains(evt.getKeyChar() + "")) {
                evt.consume();
            }
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, "Informação inserida não está correto!!!", "Erro", JOptionPane.OK_OPTION, JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_txtNomeCompletoKeyTyped

    private void txtCidadeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCidadeKeyTyped
        //validando para nao aceitar numero no campo cidade

        try {
            String caracteres = "0987654321";
            if (caracteres.contains(evt.getKeyChar() + "")) {
                evt.consume();
            }
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, "Informação inserida não está correto!!!", "Erro", JOptionPane.OK_OPTION, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtCidadeKeyTyped

    private void txtRuaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRuaKeyTyped
        //validando para nao aceitar numero no campo Rua
        try {
            String caracteres = "0987654321";
            if (caracteres.contains(evt.getKeyChar() + "")) {
                evt.consume();
            }
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, "Informação inserida não está correto!!!", "Erro", JOptionPane.OK_OPTION, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtRuaKeyTyped

    private void txtBairroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBairroKeyTyped
        // Validando para nao aceitar numero no campo bairro 

        try {
            String caracteres = "0987654321";
            if (caracteres.contains(evt.getKeyChar() + "")) {
                evt.consume();
            }
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, "Informação inserida não está correto!!!", "Erro", JOptionPane.OK_OPTION, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtBairroKeyTyped

    private void ftxtNumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ftxtNumeroKeyTyped
        // validando para não aceitar string no campo numero

        try {
            String caracteres = "0987654321";
            if (!caracteres.contains(evt.getKeyChar() + "")) {
                evt.consume();
            }
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, "Informação inserida não está correto!!!", "Erro", JOptionPane.OK_OPTION, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ftxtNumeroKeyTyped

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed

    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyTyped


    }//GEN-LAST:event_txtEmailKeyTyped

    private void txtdataNascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdataNascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdataNascActionPerformed

    private void txtNomeCompletoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeCompleto2KeyTyped
        //validando para nao aceitar numero no campo nome completo
        try {
            String caracteres = "0987654321";
            if (caracteres.contains(evt.getKeyChar() + "")) {
                evt.consume();
            }
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, "Informação inserida não está correto!!!", "Erro", JOptionPane.OK_OPTION, JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_txtNomeCompleto2KeyTyped

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        // validando para não aceitar e-mail inválido
        String email = txtEmail.getText();

        //Valida email
        boolean validaemail = valida.validaEmail(email);

        if (validaemail == true) {
            //jLblValida.setText(certo);
            jLblValida.setIcon(new ImageIcon(getClass().getResource("/Icones/Certo.png")));
        } else {
            // jLblValida.setText("E-Mail Incorreto!");
            jLblValida.setIcon(new ImageIcon(getClass().getResource("/Icones/Errado.png")));
        }

    }//GEN-LAST:event_txtEmailFocusLost

    private void txtdataNascFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtdataNascFocusGained
        // validando para não aceitar uma data inválida
        txtdataNasc.setText("");

    }//GEN-LAST:event_txtdataNascFocusGained

    private void ftxtCEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftxtCEPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftxtCEPActionPerformed

    private void txtNomeCompleto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeCompleto2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeCompleto2ActionPerformed

    private void ftxtCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftxtCidadeActionPerformed

    }//GEN-LAST:event_ftxtCidadeActionPerformed

    private void ftxtCidadeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ftxtCidadeKeyTyped
        // try catch oara não aceitar int no campo cidade

        try {
            String caracteres = "0987654321";
            if (caracteres.contains(evt.getKeyChar() + "")) {
                evt.consume();
            }
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, "Informação inserida não está correto!!!", "Erro", JOptionPane.OK_OPTION, JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_ftxtCidadeKeyTyped

    private void ftxtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftxtNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftxtNumeroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ComboEnd;
    private javax.swing.JComboBox ComboEstado;
    private javax.swing.JButton btnConcluirC;
    private javax.swing.JButton btnSair;
    private javax.swing.ButtonGroup btngSexo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JFormattedTextField ftxtCEP;
    private javax.swing.JFormattedTextField ftxtCPF;
    private javax.swing.JFormattedTextField ftxtCidade;
    private javax.swing.JFormattedTextField ftxtNumero;
    private javax.swing.JFormattedTextField ftxtTel1;
    private javax.swing.JFormattedTextField ftxtTel2;
    private javax.swing.JLabel jLblValida;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCEP;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblComplemento;
    private javax.swing.JLabel lblContato;
    private javax.swing.JLabel lblDataNasc;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblRua;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblTel1;
    private javax.swing.JLabel lblTel2;
    private javax.swing.JLabel lblTipoEndereco;
    private javax.swing.JRadioButton rbtFeminino;
    private javax.swing.JRadioButton rbtMasculino;
    private javax.swing.JRadioButton rbtOutro;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtComplemento;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNomeCompleto2;
    private javax.swing.JTextField txtRua;
    private javax.swing.JFormattedTextField txtdataNasc;
    // End of variables declaration//GEN-END:variables
}
